const { userDetail } = require("../controllers/userController");

const success = {
  signUp: "User signUp successfully",
  logged: "User loggedIn successfully",
  deleted: "User Deleted",
  update: "User detailed Update",
  email: "email send succesfully",
  contactUs: "Contact message received successfully",
  subscriptionAdd: "Subscription added successfully",
  subscriptionList: "Subscription list fetched successfully",
  subscriptionBuy: "Subscription purchased successfully",
  subscriptionDetail: "Subscription details fetched successfully",
  TodaysubscriptionList: "Today's expired subscriptions fetched successfully",
  subscriptionExpireAfter15Days:
    "Subscriptions expiring in the next 15 days fetched successfully",
  dashboardApi: "Dashboard data fetched successfully",
  tourCreate: "Tour created successfully",
  tourList: "Tour list fetched successfully",
  tourDetail: "Tour details fetched successfully",
  tourUpdate: "Tour updated successfully",
  tourDelete: "Tour deleted successfully",
  tourBook: "Tour booked successfully",
  otp: "OTP sent successfully",
  passwordReset: "Password reset email sent successfully",
  passwordChange: "Password changed successfully",
  loggedOut: "User logged out successfully",
  updateProfile: "Profile updated successfully",
  userSave: "User saved successfully",
  resetLink: "Reset link sent to the email",
  getCategory: "Category list Fecthed",
  userDetail: "Detail Fetched",
  favourite: "favourite Added",
  favouriteList: "Favourite List Fetched",
  booked: "Appointment Booked",
  image: "Image Not Found",
  documents: "documents Uploaded",
  report: "documents Fetched successfully",
  myBooking: "Bookings Fetched",
  review: "review added",
  fetchReview: "Reviews founds",
  createSubCate: "subCategory added",
  getSubCate: "subCategory fecthed",
  products: "Products Fetched",
  productadd: "Product added to cart",
  cartProduct: "cart Product fetched",
  remove: "Product Remove",
  newAdd: "Address Added",
  getAdd: "Address fetched",
};

const failure = {
  signUp: "User not signUp Error",
  logged: "User not loggedIn Error",
  notFound: "Subscription not found",
  password: "Invalid Password",
  email: "Email already exists",
  otp: "Invalid OTP",
  token: "Invalid Token",
  user: "User not found",
  subscription: "Subscription not found",
  tour: "Tour not found",
  file: "File not found",
  loggedIn: "User already logged in",
  userExists: "User already exists",
  files: "file not uploaded",
  invalid: "Invalid Credentials",
  Product: "Product Not found",
};

const err = {
  server: "Server Error",
};

module.exports = {
  successe: success,
  failures: failure,
  err: err,
};
